### ISSUE TITLE
Support `exclude` to filter out `from` in matcher

### ISSUE THREAD

**Issue by navignaw** [sshelll/telescope-switch.nvim#1]
Would it be possible to add an "exclude" field in addition to "from" that filters out file paths? My specific use case is that I have two matchers for jumping between `*.ts` and `*.test.ts` files:

```lua
matchers = {
  {
    name = "implementation",
    from = "(.*)/(.*).test.ts(x?)$",
    to = "%1/%2.ts%3",
  },
  {
    name = "test",
    from = "(.*)/(.*).ts(x?)$",
    to = "%1/%2.test.ts%3",
  },
}
```

However, I'd like to exclude the pattern `*.test.ts` from the second matcher, or it ends up chaining a file `foo.test.ts` to `foo.test.test.ts`.

I've attempted to do this via regex but Lua patterns don't seem to support negative lookahead like other regex :(

PS: love the UI and use of telescope preview as well!

**Comment by sshelll** [comment]
Hi~ Glad to see your feedback @navignaw ! I've noticed the problem that you mentioned.

I use golang in my daily work. In golang we usually write source code in a file like `foo.go` and the corresponding test file is in the same dir named `foo_test.go`.

And when I call `switch` in the test file, I also get an unexpected file named `foo_test_test.go`. But I didn't fix that problem when I noticed this issue.

But now I'm glad to fix that~

Here're some simple questions:
1. Are we talking about the same problem?
2. Which solution do you prefer?
Here is one of my thought: add an field like `ignore` in matcher -- if there're already some match results produced by other matchers, and the current matcher is 'ignored', then skip this matcher. Also we might need another field like `priority` to control the match order?

**Comment by navignaw** [comment]
1. Yes, that's the same problem I'm talking about!
2. I like the solution of adding an optional ignore matcher. I'm not sure if my specific use case would need a priority but it seems like a nice addition to have!

**Comment by sshelll** [comment]
Nice! I think I will start working on this feature this weekend:)

**Comment by sshelll** [comment]
#2 this feature is supported.

You can use a new optional field named `ignore_by` to filter result:
```lua
switch  = {
    matchers = {
        {
            name = 'go test',
            from = '(.*).go$',
            to = '%1_test.go'
            ignore_by = { 'go impl' }, -- ignore this matcher if 'go impl' matches any files
        },
        {
            name = 'go impl',
            from = '(.*)_test.go$',
            to = '%1.go'
        },
    }
}
```

Thanks for your feedback again~ @navignaw
